In [1]:
my_list=[1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]


In [2]:
import numpy as np

In [3]:
array=np.array(my_list,dtype=int)
print(array)

[1 2 3 4 5]


In [4]:
print(type(array))

<class 'numpy.ndarray'>


In [5]:
print(len(array))

5


In [6]:
print(array.ndim)

1


In [7]:
print(array.shape)

(5,)


In [9]:
np.insert(array,5,6)

array([1, 2, 3, 4, 5, 6])

In [11]:
array

array([1, 2, 3, 4, 5])

In [12]:
array=np.insert(array,5,6)
print(array)

[1 2 3 4 5 6]


In [15]:
array2=array.reshape(3,2)

In [16]:
print(array2)
array2.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [17]:
array3=array.reshape(3,-1)
print(array3)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
print(array3.ndim)

2


In [20]:
my_list2=[1,2,3,4,5]
my_list3=[2,3,4,5,6]
my_list4=[9,7,6,8,9]

mul_arr=np.array([my_list2,my_list3,my_list4])
print(mul_arr)

print(mul_arr.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
(3, 5)


In [22]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [24]:
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [26]:
#using reshape function to reshape the array
b=a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [27]:
r= range(24)
print(r)

range(0, 24)


In [30]:
#an array of evenly spaced numbers
a=np.arange(24)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [31]:
a.shape=(4,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [32]:
#reshaping the array 'a'
b=a.reshape(6,4,1)
print(b)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


In [33]:
#numpy.itemsize
#This array attribute returns the length of each element of array in bytes
#dtype of array is int8 (1 byte)
x= np.array([1,2,3,4,5],dtype=np.int8)
print(x.itemsize)

1


In [34]:
#dtype of array is now float32(4 bytes)
x=np.array([1,2,3,4,5],dtype=np.float32)
print(x.itemsize)

4


In [37]:
#numpy arithmetic operations
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)
print(x)
print(x.itemsize)
print(y)
print(y.itemsize)
print(x.itemsize==y.itemsize)

[[1. 2.]
 [3. 4.]]
8
[[5. 6.]
 [7. 8.]]
8
True


In [38]:
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [40]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [41]:
print(x*y)
print(np.multiply(x,y))
print(x.dot(y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[19. 22.]
 [43. 50.]]


In [42]:
print(x.dot(y))
print(np.dot(x,y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [43]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
